@baseUrl = http://localhost:3000

### Try to login an unknow user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Login the default admin
# @name manager
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"1",
    "password":"manager"
}


### Create the manager user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "email": "mymail",
    "username":"admin",
    "password":"admin"
}

### Login the manager user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

###
GET {{baseUrl}}/users/

