@baseUrl = http://localhost:3000



###
GET {{baseUrl}}/mots/

###
GET {{baseUrl}}/mots/1



###
GET {{baseUrl}}/mots/random
#hello
###
POST {{baseUrl}}/mots/
Content-Type: application/json

{
    "mot": "libellule",
    "semblable": "insecte"
}