@baseUrl = http://localhost:3000



###
GET {{baseUrl}}/motsTemporaires/


###
POST {{baseUrl}}/motsTemporaires/
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "mot": "fraise",
    "semblable": "cerise"
    
}

### Try to login an unknow user
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"1",
    "password":"1"
}


###

PATCH {{baseUrl}}/motsTemporaires/1
Content-Type: application/json
Authorization: {{admin.response.body.token}}

{
    "isOk": true
}