@baseUrl = http://localhost:3000



###
GET {{baseUrl}}/motsTemporaires/


###
POST {{baseUrl}}/motsTemporaires/
Content-Type: application/json

{
    "mot": "fraise",
    "semblable": "cerise"
    
}

###
PATCH {{baseUrl}}/motsTemporaires/1
Content-Type: application/json

{
    "isOk": true
}