
@baseUrl= http://localhost:3000

###
GET {{baseUrl}}/parties/

###
GET {{baseUrl}}/parties/1



### Create a pizza by using the admin account
#### First login as the admin
##### Define a request variable nammed admin :
# @name admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}
###
POST {{baseUrl}}/parties/
Content-Type: application/json
Authorization: {{admin.response.body.token}}


{
    "nombreJoueurs":9,
    "nombreIncognitos":1,
    "nombreMrXX":3,
    "idMembre":1

}