
@baseUrl= http://localhost:3000

###
GET {{baseUrl}}/parties/

###
GET {{baseUrl}}/parties/1

###
POST {{baseUrl}}/parties/
Content-Type: application/json

{
    "nbrJoueurs":4,
    "nbrIncognitos":0,
    "nbrEspions":3,
    "idMembre":1

}